config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :coordinator_positions
  resources :coordinator_statuses
  resources :officer_positions
  resources :officer_statuses
  resources :member_statuses
  get 'check_in_menu/index'
  get 'reports/index'
  resources :coordinator_check_ins
  resources :coordinators
  resources :officer_check_ins
  resources :officers
  resources :member_check_ins
  resources :events
  resources :event_types
  resources :event_statuses
  resources :sponsors
  resources :sponsor_types
  resources :members
  resources :student_classes
  resources :states
  resources :countries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get "", to: "welcome#index", as: "home"
  get "/reports", to: "reports#index", as: "reports"
  get "/check_in_menu", to: "check_in_menu#index", as: "check_in_menu"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<title>Logic Glass</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="w3-top">
  <div class="w3-bar w3-blue w3-card w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <%= link_to "Home", home_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <%= link_to "Events", events_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <%= link_to "Members", members_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <%= link_to "Officers", officers_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <%= link_to "Coordinators", coordinators_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <%= link_to "Sponsors", sponsors_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <%= link_to "Reports", reports_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %>
    <% if current_user %>
    <div style="display: flex; justify-content: flex-end"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %></div>
    <% else %>
    <div style="display: flex; justify-content: flex-end"><%= link_to 'Log In', new_user_session_path, class: "w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" %></div>
    <% end %>
  </div>

  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <%= link_to "Home", home_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <%= link_to "Events", events_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <%= link_to "Members", members_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <%= link_to "Officers", officers_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <%= link_to "Coordinators", coordinators_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <%= link_to "Sponsors", sponsors_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <%= link_to "Reports", reports_path, class: "w3-bar-item w3-button w3-padding-large" %>
    <% if current_user %>
    <div style="display: flex; justify-content: flex-end"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "w3-bar-item w3-button w3-padding-large" %></div>
    <% else %>
    <div style="display: flex; justify-content: flex-end"><%= link_to 'Log In', new_user_session_path, class: "w3-bar-item w3-button w3-padding-large" %></div>
    <% end %>
  </div>
</div>

<header class="w3-container w3-blue w3-center" style="padding:60px 16px">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= image_tag("aitplogo.png") %>
  <h2 class="w3-margin w3-jumbo">AITP Check-In App</h2><br>
  <%= link_to "Launch Check-In", check_in_menu_path, class: "w3-button w3-black w3-padding-large w3-large w3-margin-top"%>
</header>
<div class="otherblue">
<div class="w3-container">
    <div class="cot">
    <%= image_tag("cot.jpg")%>
    </div>
    </div>
</div>

<div class="otherblue w3-padding-64 w3-container">
  <div class="w3-center">
      <%= image_tag("staff.jpg") %>
      </div>
</div>

<div class="w3-container w3-black w3-center w3-opacity w3-padding-24">
  <%= image_tag("logiclogo.png", class: "logo") %>
    <h2 class="w3-margin w3-large">Provided to University of Houston AITP</h2>
    <p><%= link_to "Website", "https://aitpuh.org/", :target => "_blank" %></p>
    <i class="fa fa-twitter w3-hover-opacity"><%= link_to "Twitter", "https://twitter.com/UHaitp", :target => "_blank" %></i>
</div>


<script>
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>