config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :coordinator_positions
  resources :coordinator_statuses
  resources :officer_positions
  resources :officer_statuses
  resources :member_statuses
  get 'check_in_menu/index'
  get 'reports/index'
  resources :coordinator_check_ins
  resources :coordinators
  resources :officer_check_ins
  resources :officers
  resources :member_check_ins
  resources :events
  resources :event_types
  resources :event_statuses
  resources :sponsors
  resources :sponsor_types
  resources :members
  resources :student_classes
  resources :states
  resources :countries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get "", to: "welcome#index", as: "home"
  get "/reports", to: "reports#index", as: "reports"
  get "/check_in_menu", to: "check_in_menu#index", as: "check_in_menu"
end

app/models/coordinator_check_in.rb
class CoordinatorCheckIn < ApplicationRecord
  belongs_to :coordinator
  belongs_to :event
  def self.search(search)
      if search
       self.joins(:coordinator, :event).where(
         'coordinators.last_name LIKE ? OR events.description LIKE ? OR coordinators.first_name LIKE ?',
         "%#{search}%", "%#{search}%","%#{search}%")

      else
        self.all
      end
    end
  end 

app/controllers/coordinator_check_ins_controller.rb
class CoordinatorCheckInsController < ApplicationController
  before_action :set_coordinator_check_in, only: [:show, :edit, :update, :destroy]


  def event_name
    @events = Event.category + Event.event_date
  end
  # GET /coordinator_check_ins
  # GET /coordinator_check_ins.json
  def index
    @coordinator_check_ins = CoordinatorCheckIn.search(params[:search])
  end

  # GET /coordinator_check_ins/1
  # GET /coordinator_check_ins/1.json
  def show
  end

  # GET /coordinator_check_ins/new
  def new
    @coordinator_check_in = CoordinatorCheckIn.new
  end

  # GET /coordinator_check_ins/1/edit
  def edit
  end

  # POST /coordinator_check_ins
  # POST /coordinator_check_ins.json
  def create
    @coordinator_check_in = CoordinatorCheckIn.new(coordinator_check_in_params)

    respond_to do |format|
      if @coordinator_check_in.save
        format.html { redirect_to @coordinator_check_in, notice: 'Coordinator check in was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator_check_in }
      else
        format.html { render :new }
        format.json { render json: @coordinator_check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinator_check_ins/1
  # PATCH/PUT /coordinator_check_ins/1.json
  def update
    respond_to do |format|
      if @coordinator_check_in.update(coordinator_check_in_params)
        format.html { redirect_to @coordinator_check_in, notice: 'Coordinator check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator_check_in }
      else
        format.html { render :edit }
        format.json { render json: @coordinator_check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinator_check_ins/1
  # DELETE /coordinator_check_ins/1.json
  def destroy
    @coordinator_check_in.destroy
    respond_to do |format|
      format.html { redirect_to coordinator_check_ins_url, notice: 'Coordinator check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator_check_in
      @coordinator_check_in = CoordinatorCheckIn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coordinator_check_in_params
      params.require(:coordinator_check_in).permit(:coordinator_id, :event_id, :check_in_date)
    end
end

app/helpers/coordinator_check_ins_helper.rb
module CoordinatorCheckInsHelper
end

app/views/coordinator_check_ins/_form.html.erb
<div class="checkin-container">
<%= form_with(model: coordinator_check_in, local: true, html: {class: "checkin-form"}) do |form| %>
  <% if coordinator_check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coordinator_check_in.errors.count, "error") %> prohibited this coordinator_check_in from being saved:</h2>

      <ul>
        <% coordinator_check_in.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coordinator_id, class: "required" %>
    <%= form.collection_select :coordinator_id, Coordinator.all, :id, :full_name, {:prompt => 'Select Coordinator'} %>
  </div>

  <div class="field">
    <%= form.label :event_id, class: "required" %>
    <%= form.collection_select :event_id, Event.all, :id, :description, {:prompt => 'Select Event'} %>
  </div>

  <div class="field">
    <%= form.label :check_in_date, class: "required" %>
    <%= form.datetime_select :check_in_date, :start_year => Date.current.year, :end_year => 1920, :ampm => true, order: [:month, :day, :year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


  <%= link_to 'Back', coordinator_check_ins_path %>
<% end %>
</div>

app/views/coordinator_check_ins/_form2.html.erb
<div class="checkin-container">
<%= form_with(model: coordinator_check_in, local: true, html: {class: "checkin-form"}) do |form| %>
  <% if coordinator_check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coordinator_check_in.errors.count, "error") %> prohibited this coordinator_check_in from being saved:</h2>

      <ul>
        <% coordinator_check_in.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coordinator_id, class: "required" %>
    <%= form.collection_select :coordinator_id, Coordinator.all, :id, :full_name, {:prompt => 'Select Coordinator'} %>
  </div>

  <div class="field">
    <%= form.label :event_id, class: "required" %>
    <%= form.collection_select :event_id, Event.all, :id, :description, {:prompt => 'Select Event'} %>
  </div>

  <div class="field">
    <%= form.label :check_in_date, class: "required" %>
    <%= form.datetime_select :check_in_date, :start_year => Date.current.year, :end_year => 1920, :ampm => true, order: [:month, :day, :year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Show', @coordinator_check_in, class: "backbtn" %> |
<%= link_to 'Back', coordinator_check_ins_path, class: "backbtn" %>
</div>

app/views/coordinator_check_ins/edit.html.erb
<div class="background">
<h1>Editing Coordinator Check In</h1>

<%= render 'form2', coordinator_check_in: @coordinator_check_in %>

</div>

app/views/coordinator_check_ins/index.html.erb
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.js"></script>

  <script src="https://drvic10k.github.io/bootstrap-sortable/Scripts/bootstrap-sortable.js"></script>

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<div class="background">
<p id="notice"><%= notice %></p>
<div class="w3-center"><%= link_to "Member Check In", member_check_ins_path, class: "minimenu" %>
<%= link_to "Officer Check In", officer_check_ins_path, class: "minimenu" %>
<%= link_to "Coordinator Check In", coordinator_check_ins_path, class: "minimenu" %></div>
<h1>Coordinator Check-Ins</h1>

<div class ="search_bar">
    <%= form_tag coordinator_check_ins_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search" %>
    <% end %>
    <br>
  </div>
<section class="">
<div class="table107">
  <%= link_to 'New Coordinator Check In', new_coordinator_check_in_path, class: "add" %> <%= link_to 'Back', check_in_menu_path, class: "backbtn" %>
<table class="table table-bordered sortable">
  <thead>
    <tr class="table100-head">
      <th class="column1">Coordinator</th>
      <th>Event</th>
      <th>Check-In Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinator_check_ins.each do |coordinator_check_in| %>
      <tr>
        <td class="column1"><%= coordinator_check_in.coordinator.full_name %></td>
        <td><%= coordinator_check_in.event.description %></td>
        <td><%= coordinator_check_in.check_in_date.strftime("%b %e %Y %I:%M %p") %></td>
        <td><%= link_to 'View Check In', coordinator_check_in, class: "show" %></td>
        <td><%= link_to 'Edit Check In', edit_coordinator_check_in_path(coordinator_check_in), class: "show" %></td>
        <td><%= link_to 'Delete', coordinator_check_in, method: :delete, data: { confirm: 'Are you sure?' }, class: "show" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>
</div>

app/views/coordinator_check_ins/new.html.erb
<div class="background">
<h1>New Coordinator Check In</h1>

<%= render 'form', coordinator_check_in: @coordinator_check_in %>

<%= link_to 'Back', coordinator_check_ins_path , class: "backbtn"%>
</div>

app/views/coordinator_check_ins/show.html.erb
<div class="background">
<p id="notice"><%= notice %></p>
<div class="show-box">
<div class="show-container">
  <h1>Coordinator Check In</h1><br>
<ul class="w3-ul w3-xlarge">
<li>
  <strong>Coordinator:</strong>
  <%= @coordinator_check_in.coordinator.full_name %>
</li>

<li>
  <strong>Event:</strong>
  <%= @coordinator_check_in.event.description %>
</li>

<li>
  <strong>Check In Time:</strong>
  <%= @coordinator_check_in.check_in_date.strftime("%I:%M %p") %>
</li>

<%= link_to 'Edit', edit_coordinator_check_in_path(@coordinator_check_in), class: "backbtn" %> |
<%= link_to 'Back', coordinator_check_ins_path, class: "backbtn" %>
</div>
</div>
</div>