config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :coordinator_positions
  resources :coordinator_statuses
  resources :officer_positions
  resources :officer_statuses
  resources :member_statuses
  get 'check_in_menu/index'
  get 'reports/index'
  resources :coordinator_check_ins
  resources :coordinators
  resources :officer_check_ins
  resources :officers
  resources :member_check_ins
  resources :events
  resources :event_types
  resources :event_statuses
  resources :sponsors
  resources :sponsor_types
  resources :members
  resources :student_classes
  resources :states
  resources :countries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get "", to: "welcome#index", as: "home"
  get "/reports", to: "reports#index", as: "reports"
  get "/check_in_menu", to: "check_in_menu#index", as: "check_in_menu"
end

app/models/coordinator_position.rb
class CoordinatorPosition < ApplicationRecord
  has_many :coordinators, dependent: :destroy
  validates :position, :format => { :with => /^[a-zA-Z\s]+$/, :message => "Only letters allowed", :multiline => true }, length: { in: 2..50 }, :presence => true
  validates :description, :format => { :with => /^[a-zA-Z\s]+$/, :message => "Only letters allowed", :multiline => true }, length: { in: 2..100 }, :allow_blank => true
end

app/controllers/coordinator_positions_controller.rb
class CoordinatorPositionsController < ApplicationController
  before_action :set_coordinator_position, only: [:show, :edit, :update, :destroy]

  # GET /coordinator_positions
  # GET /coordinator_positions.json
  def index
    @coordinator_positions = CoordinatorPosition.all
  end

  # GET /coordinator_positions/1
  # GET /coordinator_positions/1.json
  def show
  end

  # GET /coordinator_positions/new
  def new
    @coordinator_position = CoordinatorPosition.new
  end

  # GET /coordinator_positions/1/edit
  def edit
  end

  # POST /coordinator_positions
  # POST /coordinator_positions.json
  def create
    @coordinator_position = CoordinatorPosition.new(coordinator_position_params)

    respond_to do |format|
      if @coordinator_position.save
        format.html { redirect_to @coordinator_position, notice: 'Coordinator position was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator_position }
      else
        format.html { render :new }
        format.json { render json: @coordinator_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinator_positions/1
  # PATCH/PUT /coordinator_positions/1.json
  def update
    respond_to do |format|
      if @coordinator_position.update(coordinator_position_params)
        format.html { redirect_to @coordinator_position, notice: 'Coordinator position was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator_position }
      else
        format.html { render :edit }
        format.json { render json: @coordinator_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinator_positions/1
  # DELETE /coordinator_positions/1.json
  def destroy
    @coordinator_position.destroy
    respond_to do |format|
      format.html { redirect_to coordinator_positions_url, notice: 'Coordinator position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator_position
      @coordinator_position = CoordinatorPosition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coordinator_position_params
      params.require(:coordinator_position).permit(:position, :description)
    end
end

app/helpers/coordinator_positions_helper.rb
module CoordinatorPositionsHelper
end

app/views/coordinator_positions/_form.html.erb
<%= form_with(model: coordinator_position, local: true) do |form| %>
  <% if coordinator_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coordinator_position.errors.count, "error") %> prohibited this coordinator_position from being saved:</h2>

      <ul>
        <% coordinator_position.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position, class: "required" %>
    <%= form.text_field :position, :size=>"25" %>
  </div>

  <div class="field">
    <%= form.label :description, class: "required" %>
    <%= form.text_field :description, :size=>"100" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coordinator_positions/edit.html.erb
<div class="background">
<h1>Editing Coordinator Position</h1>

<%= render 'form', coordinator_position: @coordinator_position %>

<%= link_to 'Show', @coordinator_position %> |
<%= link_to 'Destroy', @coordinator_position, method: :delete, data: { confirm: 'Are you sure? This will delete all rows associated with coordinators assigned to this position' } %> |
<%= link_to 'Back', coordinator_positions_path %>
</div>

app/views/coordinator_positions/index.html.erb
<div class="background">
<p id="notice"><%= notice %></p>

<h1>Coordinator Positions</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinator_positions.each do |coordinator_position| %>
      <tr>
        <td><%= coordinator_position.position %></td>
        <td><%= coordinator_position.description %></td>
        <td><%= link_to 'View Position', coordinator_position, class: "show" %></td>
        <td><%= link_to 'Edit Position', edit_coordinator_position_path(coordinator_position), class: "show" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coordinator Position', new_coordinator_position_path %>
</div>

app/views/coordinator_positions/new.html.erb
<div class="background">
<h1>New Coordinator Position</h1>

<%= render 'form', coordinator_position: @coordinator_position %>

<%= link_to 'Back', coordinator_positions_path %>
</div>

app/views/coordinator_positions/show.html.erb
<div class="background">
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @coordinator_position.position %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coordinator_position.description %>
</p>

<%= link_to 'Edit', edit_coordinator_position_path(@coordinator_position) %> |
<%= link_to 'Back', coordinator_positions_path %>
</div>