config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :coordinator_positions
  resources :coordinator_statuses
  resources :officer_positions
  resources :officer_statuses
  resources :member_statuses
  get 'check_in_menu/index'
  get 'reports/index'
  resources :coordinator_check_ins
  resources :coordinators
  resources :officer_check_ins
  resources :officers
  resources :member_check_ins
  resources :events
  resources :event_types
  resources :event_statuses
  resources :sponsors
  resources :sponsor_types
  resources :members
  resources :student_classes
  resources :states
  resources :countries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get "", to: "welcome#index", as: "home"
  get "/reports", to: "reports#index", as: "reports"
  get "/check_in_menu", to: "check_in_menu#index", as: "check_in_menu"
end

app/models/member_check_in.rb
class MemberCheckIn < ApplicationRecord
  belongs_to :member
  belongs_to :event
  def self.search(search)
  if search
   self.joins(:member,:event).where(
     'members.last_name LIKE ? OR events.description LIKE ? OR members.first_name LIKE ?',
      "%#{search}%", "%#{search}%","%#{search}%")

  else
    self.all
  end
end
end

app/controllers/member_check_ins_controller.rb
class MemberCheckInsController < ApplicationController
  before_action :set_member_check_in, only: [:show, :edit, :update, :destroy]


  def event_name
    @events = Event.category + Event.event_date
  end

  # GET /member_check_ins
  # GET /member_check_ins.json
  def index
    @member_check_ins = MemberCheckIn.search(params[:search])
  end

  # GET /member_check_ins/1
  # GET /member_check_ins/1.json
  def show
  end

  # GET /member_check_ins/new
  def new
    @member_check_in = MemberCheckIn.new
  end

  # GET /member_check_ins/1/edit
  def edit
  end

  # POST /member_check_ins
  # POST /member_check_ins.json
  def create
    @member_check_in = MemberCheckIn.new(member_check_in_params)

    respond_to do |format|
      if @member_check_in.save
        format.html { redirect_to @member_check_in, notice: 'Member check in was successfully created.' }
        format.json { render :show, status: :created, location: @member_check_in }
      else
        format.html { render :new }
        format.json { render json: @member_check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_check_ins/1
  # PATCH/PUT /member_check_ins/1.json
  def update
    respond_to do |format|
      if @member_check_in.update(member_check_in_params)
        format.html { redirect_to @member_check_in, notice: 'Member check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_check_in }
      else
        format.html { render :edit }
        format.json { render json: @member_check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_check_ins/1
  # DELETE /member_check_ins/1.json
  def destroy
    @member_check_in.destroy
    respond_to do |format|
      format.html { redirect_to member_check_ins_url, notice: 'Member check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_check_in
      @member_check_in = MemberCheckIn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_check_in_params
      params.require(:member_check_in).permit(:member_id, :event_id, :check_in_date)
    end
end

app/helpers/member_check_ins_helper.rb
module MemberCheckInsHelper
end

app/views/member_check_ins/_form.html.erb
<div class="checkin-container">
<%= form_with(model: member_check_in, local: true, html: {class: "checkin-form"}) do |form| %>
  <% if member_check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member_check_in.errors.count, "error") %> prohibited this member_check_in from being saved:</h2>

      <ul>
        <% member_check_in.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id, class: "required" %>
    <%= form.collection_select :member_id, Member.all, :id, :full_name, {:prompt => 'Select Member'} %>
  </div>

  <div class="field">
    <%= form.label :event_id, class: "required" %>
    <%= form.collection_select :event_id, Event.all, :id, :description, {:prompt => 'Select Event'} %>
  </div>

  <div class="field">
    <%= form.label :check_in_date, class: "required" %>
    <%= form.datetime_select :check_in_date, :start_year => Date.current.year, :end_year => 1920, :ampm => true, order: [:month, :day, :year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


  <%= link_to 'Back', member_check_ins_path %>
<% end %>
</div>

app/views/member_check_ins/_form2.html.erb
<div class="checkin-container">
<%= form_with(model: member_check_in, local: true, html: {class: "checkin-form"}) do |form| %>
  <% if member_check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member_check_in.errors.count, "error") %> prohibited this member_check_in from being saved:</h2>

      <ul>
        <% member_check_in.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id, class: "required" %>
    <%= form.collection_select :member_id, Member.all, :id, :full_name, {:prompt => 'Select Member'} %>
  </div>

  <div class="field">
    <%= form.label :event_id, class: "required" %>
    <%= form.collection_select :event_id, Event.all, :id, :description, {:prompt => 'Select Event'} %>
  </div>

  <div class="field">
    <%= form.label :check_in_date, class: "required" %>
    <%= form.datetime_select :check_in_date, :start_year => Date.current.year, :end_year => 1920, :ampm => true, order: [:month, :day, :year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Show', @member_check_in, class: "backbtn" %> |
<%= link_to 'Back', member_check_ins_path, class: "backbtn" %>
</div>

app/views/member_check_ins/edit.html.erb
<div class="background">
<h1>Editing Member Check In</h1>

<%= render 'form2', member_check_in: @member_check_in %>

</div>

app/views/member_check_ins/index.html.erb
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.js"></script>

  <script src="https://drvic10k.github.io/bootstrap-sortable/Scripts/bootstrap-sortable.js"></script>

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<div class="background">
<p id="notice"><%= notice %></p>
<div class="w3-center"><%= link_to "Member Check In", member_check_ins_path, class: "minimenu" %>
<%= link_to "Officer Check In", officer_check_ins_path, class: "minimenu" %>
<%= link_to "Coordinator Check In", coordinator_check_ins_path, class: "minimenu" %></div>
<h1>Member Check-Ins</h1>
<div class ="search_bar">
    <%= form_tag member_check_ins_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search" %>
    <% end %>
    <br>
  </div>
<section class="">
<div class="table105">
  <%= link_to 'New Member Check In', new_member_check_in_path, class: "add" %> <%= link_to 'Back', check_in_menu_path, class: "backbtn" %>
<table class="table table-bordered sortable">
  <thead>
    <tr class="table100-head">
      <th class="column1">Member</th>
      <th>Event</th>
      <th>Check-In Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_check_ins.each do |member_check_in| %>
      <tr>
        <td class="column1"><%= member_check_in.member.full_name %></td>
        <td><%= member_check_in.event.description %></td>
        <td><%= member_check_in.check_in_date.strftime("%b %e %Y %I:%M %p") %></td>
        <td><%= link_to 'View Check In', member_check_in, class: "show" %></td>
        <td><%= link_to 'Edit Check In', edit_member_check_in_path(member_check_in), class: "show" %></td>
        <td><%= link_to 'Delete', member_check_in, method: :delete, data: { confirm: 'Are you sure?' }, class: "show" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>
</div>

app/views/member_check_ins/new.html.erb
<div class="background">
<h1>New Member Check In</h1>

<%= render 'form', member_check_in: @member_check_in %>

<%= link_to 'Back', member_check_ins_path, class: "backbtn" %>
</div>

app/views/member_check_ins/show.html.erb
<div class="background">
<p id="notice"><%= notice %></p>
<div class="show-box">
<div class="show-container">
  <h1>Member Check In</h1><br>
<ul class="w3-ul w3-xlarge">
<li>
  <strong>Member:</strong>
  <%= @member_check_in.member.full_name %>
</li>

<li>
  <strong>Event:</strong>
  <%= @member_check_in.event.description %>
</li>

<li>
  <strong>Check In Time:</strong>
  <%= @member_check_in.check_in_date.strftime("%I:%M %p") %>
</li>

<%= link_to 'Edit', edit_member_check_in_path(@member_check_in), class: "backbtn" %> |
<%= link_to 'Back', member_check_ins_path, class: "backbtn" %>
</div>
</div>
</div>